### ISSUE TITLE
training the dependency parser

### ISSUE THREAD

**Issue by Deep911** [erickrf/nlpnet#26]
Hi,

How can we train the dependency parser only?
also the data you have used to train the dependency parser, is that an open datasource ?

Regards,
Debanjan

**Comment by erickrf** [comment]
Hi,

I haven't given much attention to documenting the dependency parser functionality since its results were below expected, but you can get the command line instructions running `nlpnet-train.py dependency -h`.

It has two stages: the unlabeled (finding the dependency edges) and labeled (labeling the previously found edges), and they are trained separately. Instructions for each are available with `nlpnet-train.py dependency unlabeled -h` and `nlpnet-train.py dependency labeled -h`
