### ISSUE TITLE
Need clarity on Dependency Relations output by Dependency Parser.

### ISSUE THREAD

**Issue by damzC** [erickrf/nlpnet#33]
Hi,

While using your dependency parser for English, I found that the dependency relations output by the parser are not in CoNLL Universal Dependency Relations format or, Stanford format. Can you please point me to a document/ page where I can find the meaning of these relations.

For eg:

For the sentence: "I want to take a leave today"
The output is:
1	I	_	PRP	PRP	_	2	SBJ
2	want	_	VBP	VBP	_	0	ROOT
3	to	_	TO	TO	_	2	OPRD
4	take	_	VB	VB	_	3	IM
5	a	_	DT	DT	_	6	NMOD
6	leave	_	NN	NN	_	4	OBJ
7	today	_	NN	NN	_	4	TMP

I cannot find what the relations 'IM', 'OPRD' mean, anywhere. The same sentence output by the Stanford dependency parser is:

1	I	 I	PRP	O	2	nsubj
2	want	 want	VBP	O	0	ROOT
3	to	to	TO	O	4	mark
4	take	take	VB	O	2	xcomp
5	a	a	DT	O	6	det
6	leave	leave	NN	O	4	dobj
7	today	today	NN	DATE	4	nmod:tmod

Can you please help me in finding the meaning of these dependency relations.

Thanks in advance.
--
Arindam

**Comment by erickrf** [comment]
Hi @damzC 
The English dependency model was trained on a version of the Penn Treebank converted with the [LTH](http://nlp.cs.lth.se/software/treebank_converter/) tool. I couldn't find any organized description of all the labels, since the Penn Treebank was originally annotated with constituent trees, but in [this page](http://www.surdeanu.info/mihai/teaching/ista555-fall13/readings/PennTreebankConstituents.html) you can find a good description.
